apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview-cracker
spec:
  selector:
    matchLabels:
      app: interview-cracker
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: interview-cracker
    spec:
      containers:
      - name: interview-cracker
        env:
        - name: MONGO_URL
          value: mongodb://cracker1:cracker1@ds119028.mlab.com:19028/cracker_db
        image: technicalbird/cracker:9.6.1

---
apiVersion: v1
kind: Service
metadata:
  name: interview-cracker

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: interview-cracker

  ports:
    - name: http
      port: 3000
      nodePort: 30091

  type: NodePort